version: "3.9"

services:
  web:
    build: ./bill_loader
    command: python manage.py runserver 0.0.0.0:8000
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: database
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_password
      - POSTGRES_DB=local_db
volumes:
  postgres_volume:
